/**
 * Aplikasi Room Management
 * @author Irene Wiliudarsan - 13513002
 * @author William Sentosa - 13513026
 * @author Angela Lynn - 13513032
 * @author Devina Ekawati - 13513088
 */
package gui;

import bookinginformation.BookingInformation;
import database.BorrowingModel;
import database.MaintenanceModel;
import database.RoomModel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;

/**
 *
 * @author angelynz95
 */
public class BookingInformationPanel extends javax.swing.JPanel {
    BookingInformation bookingInformation;
    GregorianCalendar date;
    List<String> rooms;
    List<String> schedules;

    /**
     * Creates new form BookingInformation
     */
    public BookingInformationPanel(GregorianCalendar date) {
        initComponents();
        bookingInformation = new BookingInformation();
        this.date = date;
        rooms = new ArrayList<String>();
        schedules = new ArrayList<String>();
        
        setRooms();
        setSchedules();
        customizeBookingInformationPane();
        showBookingInformation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookingInformationPane = new javax.swing.JScrollPane();
        bookingInformationPanel = new javax.swing.JPanel();

        javax.swing.GroupLayout bookingInformationPanelLayout = new javax.swing.GroupLayout(bookingInformationPanel);
        bookingInformationPanel.setLayout(bookingInformationPanelLayout);
        bookingInformationPanelLayout.setHorizontalGroup(
            bookingInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1154, Short.MAX_VALUE)
        );
        bookingInformationPanelLayout.setVerticalGroup(
            bookingInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );

        bookingInformationPane.setViewportView(bookingInformationPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(bookingInformationPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(bookingInformationPane, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setRooms() {
        for(Map.Entry<RoomModel, Map<Integer, Object>> roomSchedule: bookingInformation.getRoomsSchedule().entrySet()) {
            rooms.add(roomSchedule.getKey().getName());
        }
    }
    
    private void setSchedules() {
        for (int i = 7; i < 9; i++) {
            schedules.add("0" + i + ".00 - 0" + (i+1) + ".00");
        }
        schedules.add("09.00 - 10.00");
        for (int i = 0; i < 9; i++) {
            schedules.add("1" + i + ".00 - 1" + (i+1) + ".00");
        }
        schedules.add("19.00 - 20.00");
        for (int i = 0; i <= 2; i++) {
            schedules.add("2" + i + ".00 - 2" + (i+1) + ".00");
        }
    }
    
    private void customizeBookingInformationPane() {
        bookingInformationPane.setOpaque(false);
        bookingInformationPane.getViewport().setOpaque(false);
        bookingInformationPane.setBorder(null);
        bookingInformationPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        bookingInformationPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        bookingInformationPanel.setLayout(new GridLayout(0, rooms.size() + 1));
    }
    
    private void showBookingInformation() {
        bookingInformation.showBookingSchedule(date);
        bookingInformation.showMaintenanceSchedule(date);
        customizeRoomCells();
        customizeScheduleCells();
    }
    
    private void customizeRoomCells() {
        JLabel roomLabel;
        
        roomLabel = new JLabel();
        customizeLabel(roomLabel);
        roomLabel.setBackground(Color.lightGray);
        roomLabel.setText("");
        bookingInformationPanel.add(roomLabel);
        
        for (int i = 0; i < rooms.size(); i++) {
            roomLabel = new JLabel();
            customizeLabel(roomLabel);
            roomLabel.setBackground(Color.lightGray);
            roomLabel.setText(rooms.get(i));
            bookingInformationPanel.add(roomLabel);
        }
    }
    
    private void customizeScheduleCells() {
        JLabel scheduleLabel, timeLabel;
        
        for (int i = 0; i < schedules.size(); i++) {
            timeLabel = new JLabel();
            customizeLabel(timeLabel);
            timeLabel.setBackground(Color.lightGray);
            timeLabel.setText(schedules.get(i));
            bookingInformationPanel.add(timeLabel);
            
            for(Map.Entry<RoomModel, Map<Integer, Object>> roomSchedule: bookingInformation.getRoomsSchedule().entrySet()) {
                scheduleLabel = new JLabel();
                
                customizeLabel(scheduleLabel);
                if (roomSchedule.getValue().size() > 0) {
                    if (roomSchedule.getValue().containsKey(i + 7)) {
                        if (roomSchedule.getValue().get(i + 7).getClass().equals(BorrowingModel.class)) {
                            scheduleLabel.setBackground(new Color(138, 199, 222));
                        } else if (roomSchedule.getValue().get(i + 7).getClass().equals(MaintenanceModel.class)) {
                            scheduleLabel.setBackground(new Color(250, 127, 119));
                        }
                    }
                }
                
                bookingInformationPanel.add(scheduleLabel);
            }
        }
    }
    
    private void customizeLabel(JLabel label) {
        label.setPreferredSize(new Dimension(200, 16));
        label.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        label.setHorizontalAlignment(SwingConstants.CENTER);
        label.setVerticalAlignment(SwingConstants.CENTER);
        label.setFont(new Font("Roboto", Font.PLAIN, 16));
        label.setOpaque(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane bookingInformationPane;
    private javax.swing.JPanel bookingInformationPanel;
    // End of variables declaration//GEN-END:variables
}
