/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import borrowing.Borrowing;
import database.BorrowingModel;
import java.awt.event.WindowEvent;

/**
 *
 * @author William Sentosa
 */
public class BookingDetailFrame extends javax.swing.JFrame {
    
    private BorrowingModel borrowingModel;
    private String roomName;
    private Borrowing borrowing;
     
    public BookingDetailFrame(BorrowingModel borrowingModel, String roomName) {
        initComponents();
        this.borrowingModel = borrowingModel;
        this.roomName = roomName;
        borrowing = new Borrowing();
        setComponent();
    }

    private void setComponent() {
        jumlahPesertaLabel.setText(borrowingModel.getTotalParticipant() + "");
        namaKegiatanLabel.setText(borrowingModel.getActivityName());
        namaLembagaLabel.setText(borrowingModel.getOrganizationName());
        namaPeminjamLabel.setText(borrowingModel.getBorrowerName());
        namaRuanganLabel.setText(roomName);
        noTelpLabel.setText(borrowingModel.getBorrowerPhone());
        statusPeminjamLabel.setText(borrowingModel.getBorrowerStatus());
        waktuIzinLabel.setText(borrowingModel.getPermissionTime().getTime().toString());
        waktuMulaiLabel.setText(borrowingModel.getStartTime().getTime().toString());
        waktuSelesaiLabel.setText(borrowingModel.getFinishTime().getTime().toString());
        idPeminjamLabel.setText(borrowingModel.getBorrowerId() + "");
        alamatLabel.setText(borrowingModel.getBorrowerAddress());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        namaRuanganLabel = new javax.swing.JLabel();
        namaPeminjamLabel = new javax.swing.JLabel();
        statusPeminjamLabel = new javax.swing.JLabel();
        alamatLabel = new javax.swing.JLabel();
        idPeminjamLabel = new javax.swing.JLabel();
        noTelpLabel = new javax.swing.JLabel();
        namaKegiatanLabel = new javax.swing.JLabel();
        namaLembagaLabel = new javax.swing.JLabel();
        jumlahPesertaLabel = new javax.swing.JLabel();
        waktuMulaiLabel = new javax.swing.JLabel();
        waktuSelesaiLabel = new javax.swing.JLabel();
        waktuIzinLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1.setText("Detail Pemesanan");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Nama Ruangan ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Nama Peminjam ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Status Peminjam ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("NIM / NIP ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Alamat Peminjam ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("Nomor Telepon Peminjam ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setText("Nama Lembaga");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel9.setText("Nama Kegiatan");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel10.setText("Jumlah Peserta");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel11.setText("Waktu izin");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel12.setText("Waktu mulai");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel13.setText("Waktu selesai");

        deleteButton.setText("Hapus");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        editButton.setText("Ubah");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        namaRuanganLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        namaPeminjamLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        statusPeminjamLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        alamatLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        idPeminjamLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        noTelpLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        namaKegiatanLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        namaLembagaLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jumlahPesertaLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        waktuMulaiLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        waktuSelesaiLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        waktuIzinLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(deleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaRuanganLabel)
                            .addComponent(namaPeminjamLabel)
                            .addComponent(statusPeminjamLabel)
                            .addComponent(alamatLabel)
                            .addComponent(idPeminjamLabel)
                            .addComponent(noTelpLabel)
                            .addComponent(namaKegiatanLabel)
                            .addComponent(namaLembagaLabel)
                            .addComponent(jumlahPesertaLabel)
                            .addComponent(waktuMulaiLabel)
                            .addComponent(waktuSelesaiLabel)
                            .addComponent(waktuIzinLabel))))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(namaRuanganLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(namaPeminjamLabel))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(statusPeminjamLabel))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(idPeminjamLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(alamatLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(noTelpLabel))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(namaLembagaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(namaKegiatanLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jumlahPesertaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(waktuIzinLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(waktuMulaiLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(waktuSelesaiLabel))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(editButton))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        borrowing.deleteBorrowing(borrowingModel);
        DeleteSuccessFrame successFrame = new DeleteSuccessFrame();
        successFrame.setVisible(true);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        BorrowingFrame borrowingFrame = new BorrowingFrame(borrowingModel, roomName);
        borrowingFrame.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_editButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Borrowing b = new Borrowing();
                new BookingDetailFrame(b.searchBorrowingById(8), "R 7606").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel idPeminjamLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jumlahPesertaLabel;
    private javax.swing.JLabel namaKegiatanLabel;
    private javax.swing.JLabel namaLembagaLabel;
    private javax.swing.JLabel namaPeminjamLabel;
    private javax.swing.JLabel namaRuanganLabel;
    private javax.swing.JLabel noTelpLabel;
    private javax.swing.JLabel statusPeminjamLabel;
    private javax.swing.JLabel waktuIzinLabel;
    private javax.swing.JLabel waktuMulaiLabel;
    private javax.swing.JLabel waktuSelesaiLabel;
    // End of variables declaration//GEN-END:variables
}
