/**
 * Aplikasi Room Management
 * @author Irene Wiliudarsan - 13513002
 * @author William Sentosa - 13513026
 * @author Angela Lynn - 13513032
 * @author Devina Ekawati - 13513088
 */
package gui;

import java.awt.FlowLayout;
import javax.swing.JFrame;
import javax.swing.JTabbedPane;
import javax.swing.SwingUtilities;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author angelynz95
 */
public class MenuPanel extends javax.swing.JPanel {
    private JFrame mainFrame;
    private BookingInformation bookingInformationPanel;
    private RoomInformationPanel roomInformationPanel;
    private StatisticPanel statisticPanel;
    private ChangePasswordPanel changePasswordPanel;
    
    /**
     * Creates new form MainPanel
     */
    public MenuPanel() {
        initComponents();
        // Tampilan Organisasi Jadwal
        bookingInformationContainer.setLayout(new FlowLayout());
        bookingInformationPanel = new BookingInformation();
        bookingInformationContainer.add(bookingInformationPanel);
        
        // Tampilan Info Ruangan
        roomInformationContainer.setLayout(new FlowLayout());
        roomInformationPanel = new RoomInformationPanel();
        roomInformationContainer.add(roomInformationPanel);
        
        // Tampilan Statistik
        statisticContainer.setLayout(new FlowLayout());
        statisticPanel = new StatisticPanel();
        statisticContainer.add(statisticPanel);
        
        // Tampilan Ubah Kata Sandi
        changePasswordContainer.setLayout(new FlowLayout());
        changePasswordPanel = new ChangePasswordPanel();
        changePasswordContainer.add(changePasswordPanel);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPane = new javax.swing.JTabbedPane();
        bookingInformationContainer = new javax.swing.JPanel();
        roomInformationContainer = new javax.swing.JPanel();
        statisticContainer = new javax.swing.JPanel();
        changePasswordContainer = new javax.swing.JPanel();
        logoutLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1200, 700));

        menuPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        menuPane.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        menuPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPaneMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bookingInformationContainerLayout = new javax.swing.GroupLayout(bookingInformationContainer);
        bookingInformationContainer.setLayout(bookingInformationContainerLayout);
        bookingInformationContainerLayout.setHorizontalGroup(
            bookingInformationContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1195, Short.MAX_VALUE)
        );
        bookingInformationContainerLayout.setVerticalGroup(
            bookingInformationContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );

        menuPane.addTab("Organisasi Jadwal", bookingInformationContainer);

        javax.swing.GroupLayout roomInformationContainerLayout = new javax.swing.GroupLayout(roomInformationContainer);
        roomInformationContainer.setLayout(roomInformationContainerLayout);
        roomInformationContainerLayout.setHorizontalGroup(
            roomInformationContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1195, Short.MAX_VALUE)
        );
        roomInformationContainerLayout.setVerticalGroup(
            roomInformationContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );

        menuPane.addTab("Info Ruangan", roomInformationContainer);

        javax.swing.GroupLayout statisticContainerLayout = new javax.swing.GroupLayout(statisticContainer);
        statisticContainer.setLayout(statisticContainerLayout);
        statisticContainerLayout.setHorizontalGroup(
            statisticContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1195, Short.MAX_VALUE)
        );
        statisticContainerLayout.setVerticalGroup(
            statisticContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );

        menuPane.addTab("Statistik", statisticContainer);

        javax.swing.GroupLayout changePasswordContainerLayout = new javax.swing.GroupLayout(changePasswordContainer);
        changePasswordContainer.setLayout(changePasswordContainerLayout);
        changePasswordContainerLayout.setHorizontalGroup(
            changePasswordContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1195, Short.MAX_VALUE)
        );
        changePasswordContainerLayout.setVerticalGroup(
            changePasswordContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );

        menuPane.addTab("Ubah Kata Sandi", changePasswordContainer);

        logoutLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        logoutLabel.setText("Keluar");
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        titleLabel.setText("Room Management");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPane)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutLabel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutLabel)
                    .addComponent(titleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menuPane, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        // TODO add your handling code here:
        mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        mainFrame.setContentPane(new LoginPanel());
        mainFrame.pack();
    }//GEN-LAST:event_logoutLabelMouseClicked

    private void menuPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPaneMouseClicked
        // TODO add your handling code here:
        ChangeListener changeListener = new ChangeListener() {
            public void stateChanged(ChangeEvent changeEvent) {
              JTabbedPane sourceTabbedPane = (JTabbedPane) changeEvent.getSource();
              int index = sourceTabbedPane.getSelectedIndex();
              System.out.println("Tab changed to: " + index);
              if (index == 3) {
                  changePasswordPanel.resetTextField();
              }
              
            }
        };
        menuPane.addChangeListener(changeListener);
    }//GEN-LAST:event_menuPaneMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bookingInformationContainer;
    private javax.swing.JPanel changePasswordContainer;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JTabbedPane menuPane;
    private javax.swing.JPanel roomInformationContainer;
    private javax.swing.JPanel statisticContainer;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
