/**
 * Aplikasi Room Management
 * @author Irene Wiliudarsan - 13513002
 * @author William Sentosa - 13513026
 * @author Angela Lynn - 13513032
 * @author Devina Ekawati - 13513088
 */
package gui;

import administrator.Administrator;
import borrowing.Borrowing;
import javax.swing.JOptionPane;
import maintenance.Maintenance;

/**
 *
 * @author angelynz95
 */
public class SettingPanel extends javax.swing.JPanel {
    
    private Administrator administrator;
    
    /**
     * Creates new form ChangePasswordPanel
     */
    public SettingPanel() {
        initComponents();
        administrator = new Administrator();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oldPasswordField = new javax.swing.JPasswordField();
        newPasswordField = new javax.swing.JPasswordField();
        newPasswordConfirmationField = new javax.swing.JPasswordField();
        oldPasswordLabel = new javax.swing.JLabel();
        newPasswordLabel = new javax.swing.JLabel();
        newPasswordConfirmationLabel = new javax.swing.JLabel();
        changePasswordButton = new javax.swing.JButton();
        oldPasswordMessage = new javax.swing.JLabel();
        newPasswordConfirmationMessage = new javax.swing.JLabel();
        newPasswordMessage = new javax.swing.JLabel();
        deletePasswordLabel = new javax.swing.JLabel();
        deletePasswordButton = new javax.swing.JButton();

        oldPasswordLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        oldPasswordLabel.setText("Kata Sandi Lama");

        newPasswordLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        newPasswordLabel.setText("Kata Sandi Baru");

        newPasswordConfirmationLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        newPasswordConfirmationLabel.setText("Konfirmasi Kata Sandi Baru");

        changePasswordButton.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        changePasswordButton.setText("Ubah");
        changePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordButtonActionPerformed(evt);
            }
        });

        oldPasswordMessage.setForeground(new java.awt.Color(255, 0, 0));

        newPasswordConfirmationMessage.setForeground(new java.awt.Color(255, 0, 0));

        newPasswordMessage.setForeground(new java.awt.Color(255, 0, 0));

        deletePasswordLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        deletePasswordLabel.setText("Hapus semua data");

        deletePasswordButton.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        deletePasswordButton.setText("Hapus");
        deletePasswordButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletePasswordButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newPasswordLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newPasswordConfirmationLabel)
                            .addComponent(oldPasswordLabel)
                            .addComponent(deletePasswordLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(oldPasswordField)
                                        .addComponent(newPasswordField)
                                        .addComponent(newPasswordConfirmationField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(changePasswordButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(deletePasswordButton)))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newPasswordConfirmationMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oldPasswordMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPasswordMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oldPasswordLabel)
                    .addComponent(oldPasswordMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newPasswordMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(newPasswordLabel)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPasswordConfirmationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPasswordConfirmationLabel)
                    .addComponent(newPasswordConfirmationMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changePasswordButton)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletePasswordLabel)
                    .addComponent(deletePasswordButton))
                .addGap(144, 144, 144))
        );
    }// </editor-fold>//GEN-END:initComponents

    private String convertToString(char[] src) {
        String result  = "";
        for(int i=0; i<src.length; i++) {
            result = result + src[i];
        }
        return result;
    }
    
    public void resetTextField() {
        newPasswordConfirmationField.setText("");
        newPasswordField.setText("");
        oldPasswordField.setText("");
        oldPasswordMessage.setText("");
        newPasswordMessage.setText("");
        newPasswordConfirmationMessage.setText("");
    }
    
    private void changePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordButtonActionPerformed
        String oldPassword = convertToString(oldPasswordField.getPassword());
        String newPassword = convertToString(newPasswordField.getPassword());
        String newPasswordConfirmed = convertToString(newPasswordConfirmationField.getPassword());
        
        if (administrator.validateLogin(oldPassword)) {
            if ((newPassword.length() > 0) && (newPasswordConfirmed.length() > 0)) {
                if (newPassword.equals(newPasswordConfirmed)) {
                    if (!newPassword.equals(oldPassword)) {
                        administrator.changePassword(newPassword);
                        JOptionPane.showMessageDialog(MainFrame.getInstance(), "Kata sandi berhasil diubah", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                        resetTextField();
                    } else {
                        oldPasswordMessage.setText("");
                        newPasswordMessage.setText("Kata sandi baru tidak boleh sama");
                        newPasswordConfirmationMessage.setText("");
                    }
                } else {
                    oldPasswordMessage.setText("");
                    newPasswordConfirmationMessage.setText("Konfirmasi kata sandi salah");
                }
            } else if ((newPassword.length() == 0) && (newPasswordConfirmed.length() > 0)) {
                oldPasswordMessage.setText("");
                newPasswordMessage.setText("Kolom ini wajib diisi");
                newPasswordConfirmationMessage.setText("");
            } else if ((newPasswordConfirmed.length() == 0) && (newPassword.length() > 0)) {
                oldPasswordMessage.setText("");
                newPasswordConfirmationMessage.setText("Kolom ini wajib diisi");
                newPasswordMessage.setText("");
            } else {
                oldPasswordMessage.setText("");
                newPasswordConfirmationMessage.setText("Kolom ini wajib diisi");
                newPasswordMessage.setText("Kolom ini wajib diisi");
            }
        } else{
            newPasswordConfirmationMessage.setText("");
            oldPasswordMessage.setText("Kata sandi lama salah");
        }
    }//GEN-LAST:event_changePasswordButtonActionPerformed

    private void deletePasswordButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletePasswordButtonMouseClicked
        String message = "Apakah Anda yakin ingin menghapus seluruh jadwal?";
        String title = "Konfirmasi Penghapusan";
        Object[] options = {"Ya", "Tidak"};
        int answerId = JOptionPane.showOptionDialog(this, message, title, JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[1]);
        if (options[answerId].equals("Ya")) {
            Borrowing borrowing = new Borrowing();
            borrowing.deleteAllBorrowing();
            Maintenance maintenance = new Maintenance();
            maintenance.deleteAllMaintenance();
        }
        
    }//GEN-LAST:event_deletePasswordButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changePasswordButton;
    private javax.swing.JButton deletePasswordButton;
    private javax.swing.JLabel deletePasswordLabel;
    private javax.swing.JPasswordField newPasswordConfirmationField;
    private javax.swing.JLabel newPasswordConfirmationLabel;
    private javax.swing.JLabel newPasswordConfirmationMessage;
    private javax.swing.JPasswordField newPasswordField;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JLabel newPasswordMessage;
    private javax.swing.JPasswordField oldPasswordField;
    private javax.swing.JLabel oldPasswordLabel;
    private javax.swing.JLabel oldPasswordMessage;
    // End of variables declaration//GEN-END:variables
}
